name: lambda-depl

on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-lambda@edge
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies, Build application and Zip dist folder contents
        run: npm install && zip -qq -r -j ./bundle.zip ./src/*
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: git-deploy-to-the-edge-demo
          zip_file: bundle.zip